/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasiproject.view;

/**
 *
 * @author paolo
 */
public class MainFrameView extends javax.swing.JFrame {

    /**
     * Creates new form MainViewHolder
     */
    public MainFrameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMEmployee = new javax.swing.JMenu();
        jmiRegisterEmployee = new javax.swing.JMenuItem();
        jMSchedule = new javax.swing.JMenu();
        jMIRegisterSchedule = new javax.swing.JMenuItem();
        jMIAssignToEmployee = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMIRegisterAssistance = new javax.swing.JMenuItem();
        jMIViewTodayAssistance = new javax.swing.JMenuItem();
        jMenuJustifications = new javax.swing.JMenu();
        jMIJustify = new javax.swing.JMenuItem();
        jMIReviseJustification = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMEmployee.setText("Employee");

        jmiRegisterEmployee.setText("Register");
        jmiRegisterEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegisterEmployeeActionPerformed(evt);
            }
        });
        jMEmployee.add(jmiRegisterEmployee);

        jMenuBar1.add(jMEmployee);

        jMSchedule.setText("Schedules");

        jMIRegisterSchedule.setText("Register");
        jMIRegisterSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegisterScheduleActionPerformed(evt);
            }
        });
        jMSchedule.add(jMIRegisterSchedule);

        jMIAssignToEmployee.setText("Assign to Employee");
        jMIAssignToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAssignToEmployeeActionPerformed(evt);
            }
        });
        jMSchedule.add(jMIAssignToEmployee);

        jMenuBar1.add(jMSchedule);

        jMenu1.setText("Assistance");

        jMIRegisterAssistance.setText("Register");
        jMIRegisterAssistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegisterAssistanceActionPerformed(evt);
            }
        });
        jMenu1.add(jMIRegisterAssistance);

        jMIViewTodayAssistance.setText("View Todays");
        jMIViewTodayAssistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIViewTodayAssistanceActionPerformed(evt);
            }
        });
        jMenu1.add(jMIViewTodayAssistance);

        jMenuBar1.add(jMenu1);

        jMenuJustifications.setText("Justifications");

        jMIJustify.setText("Justify");
        jMIJustify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIJustifyActionPerformed(evt);
            }
        });
        jMenuJustifications.add(jMIJustify);

        jMIReviseJustification.setText("Revise");
        jMIReviseJustification.setToolTipText("");
        jMIReviseJustification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIReviseJustificationActionPerformed(evt);
            }
        });
        jMenuJustifications.add(jMIReviseJustification);

        jMenuBar1.add(jMenuJustifications);

        jMenuReport.setText("Report");
        jMenuBar1.add(jMenuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRegisterEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegisterEmployeeActionPerformed
        RegisterEmployeeView re = new RegisterEmployeeView();
        re.setVisible(true);
        this.add(re);
    }//GEN-LAST:event_jmiRegisterEmployeeActionPerformed

    private void jMIAssignToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAssignToEmployeeActionPerformed
        AssigntoEmployeeView atev = new AssigntoEmployeeView();
        atev.setVisible(true);
        this.add(atev);
    }//GEN-LAST:event_jMIAssignToEmployeeActionPerformed

    private void jMIViewTodayAssistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIViewTodayAssistanceActionPerformed
        TodayEmployeeAssistanceView vtea = new TodayEmployeeAssistanceView();
        vtea.setVisible(true);
        this.add(vtea);
    }//GEN-LAST:event_jMIViewTodayAssistanceActionPerformed

    private void jMIRegisterScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegisterScheduleActionPerformed
        RegisterScheduleView rsv = new RegisterScheduleView();
        rsv.setVisible(true);
        this.add(rsv);
    }//GEN-LAST:event_jMIRegisterScheduleActionPerformed

    private void jMIRegisterAssistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegisterAssistanceActionPerformed
        RegisterAssistanceView rav = new RegisterAssistanceView();
        rav.setVisible(true);
        this.add(rav);
    }//GEN-LAST:event_jMIRegisterAssistanceActionPerformed

    private void jMIJustifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIJustifyActionPerformed
        JustificatyInconsistenceView jiv = new JustificatyInconsistenceView();
        jiv.setVisible(true);
        this.add(jiv);
    }//GEN-LAST:event_jMIJustifyActionPerformed

    private void jMIReviseJustificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIReviseJustificationActionPerformed
        ListEmployeeInconsistenceJustificationView leijv = new ListEmployeeInconsistenceJustificationView();
        leijv.setVisible(true);
        this.add(leijv);
    }//GEN-LAST:event_jMIReviseJustificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrameView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMEmployee;
    private javax.swing.JMenuItem jMIAssignToEmployee;
    private javax.swing.JMenuItem jMIJustify;
    private javax.swing.JMenuItem jMIRegisterAssistance;
    private javax.swing.JMenuItem jMIRegisterSchedule;
    private javax.swing.JMenuItem jMIReviseJustification;
    private javax.swing.JMenuItem jMIViewTodayAssistance;
    private javax.swing.JMenu jMSchedule;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuJustifications;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenuItem jmiRegisterEmployee;
    // End of variables declaration//GEN-END:variables
}
